recording:
  label: real
  topics:
    - /joint_states
    - /c4g/joint_states
    - /tf
    - /tf_static
    - /arm/execute/_action/status
    - /peripherals/events
    - /peripherals/schleiftrog/state
    - /peripherals/motorspindel/state
    - /peripherals/fliehkraftgleitschleifanlage/state
    - /peripherals/festo_pneumatiksteuerung/state
    - /sensors/tool_wrench
    - /sensors/process_pressure
