/**:
  ros__parameters:
    action_name: /sim/arm/execute
    planning_group: arm
    base_frame: c4g_base
    end_effector_link: tcp_link
    pilz_pipeline_id: pilz_industrial_motion_planner
    ptp_planner_id: PTP
    lin_planner_id: LIN
    circ_planner_id: CIRC
    pilz_max_trans_velocity: 1.0
    sequence_action_name: /sequence_move_group
    max_fly_points: 20
    fly_norm_radius_safety_factor: 0.45
    sequence_wait_timeout: 10.0
    planning_time: 5.0
    planning_attempts: 10
    current_state_timeout: 2.0
    joint_overrides_percent: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    physical_joint_max_velocities: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    physical_joint_max_accelerations: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    linear_speed_mps: 0.05
    acceleration_percent: 50.0
    deceleration_percent: 50.0
    coupling_offset: 1.5708
    joint_3_min: -4.0317
    joint_3_max: 0.0
    joint_7_min: -1.151917306
    joint_7_max: 1.047197551
